openapi: 3.1.0
info:
  title: Payment Manager API
  version: 0.1.0
paths:
  /token:
    post:
      summary: Create token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '200':
          description: Token created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
  /balance/{token_id}:
    get:
      summary: Check balance
      parameters:
        - in: path
          name: token_id
          schema:
            type: string
      responses:
        '200':
          description: Balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
components:
  schemas:
    TokenRequest:
      type: object
      properties:
        budget:
          type: integer
        voice_id:
          type: string
    TokenResponse:
      type: object
      properties:
        token_id:
          type: string
        expire_in:
          type: integer
    BalanceResponse:
      type: object
      properties:
        balance:
          type: integer
